import { CarType } from "@/types";

export const cars: CarType[] = [
  {
    id: 1,
    name: "Toyota Avanza",
    brand: "Toyota",
    model: "Avanza",
    year: 2022,
    seats: 7,
    price_per_day: 350000,
    fuel_type: "Bensin",
    transmission: "Manual",
    image: "/images/toyota-avanza.png",
    description:
      "Toyota Avanza adalah mobil MPV yang cocok untuk perjalanan keluarga atau kelompok dengan kapasitas hingga 7 orang.",
    availability: true,
  },
  {
    id: 2,
    name: "Toyota Innova",
    brand: "Toyota",
    model: "Innova",
    year: 2020,
    seats: 7,
    price_per_day: 650000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/toyota-innova.png",
    description:
      "Toyota Innova adalah mobil keluarga yang nyaman dengan kapasitas hingga 7 orang dan cocok untuk perjalanan jauh.",
    availability: true,
  },
  {
    // done
    id: 3,
    name: "Toyota Fortuner",
    brand: "Toyota",
    model: "Fortuner",
    year: 2023,
    seats: 7,
    price_per_day: 900000,
    fuel_type: "Diesel",
    transmission: "Matic",
    image: "/images/toyota-fortuner.png",
    description:
      "Toyota Fortuner adalah SUV tangguh dengan performa luar biasa, cocok untuk petualangan di medan berat.",
    availability: false,
  },
  {
    id: 4,
    name: "Honda Civic",
    brand: "Honda",
    model: "Civic",
    year: 2021,
    seats: 5,
    price_per_day: 600000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/honda-civic.png",
    description:
      "Honda Civic merupakan mobil sedan dengan desain sporty dan performa yang tinggi, cocok untuk perjalanan pribadi atau bisnis.",
    availability: true,
  },
  {
    id: 5,
    name: "Honda CR-V",
    brand: "Honda",
    model: "CR-V",
    year: 2022,
    seats: 5,
    price_per_day: 750000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/honda-crv.png",
    description:
      "Honda CR-V adalah SUV kompak dengan kenyamanan dan fitur canggih, ideal untuk perjalanan jarak jauh dan keluarga.",
    availability: true,
  },
  {
    id: 6,
    name: "Honda HR-V",
    brand: "Honda",
    model: "HR-V",
    year: 2024,
    seats: 5,
    price_per_day: 500000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/honda-hrv.png",
    description:
      "Honda HR-V adalah SUV kecil dengan desain stylish dan efisiensi bahan bakar yang baik, cocok untuk penggunaan sehari-hari.",
    availability: true,
  },
  {
    id: 7,
    name: "Mitsubishi Xpander",
    brand: "Mitsubishi",
    model: "Xpander",
    year: 2022,
    seats: 7,
    price_per_day: 400000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/mitsubishi-xpander.png",
    description:
      "Mitsubishi Xpander adalah MPV dengan desain modern dan fitur yang lengkap, ideal untuk keluarga besar.",
    availability: true,
  },
  {
    id: 8,
    name: "Mitsubishi Pajero Sport",
    brand: "Mitsubishi",
    model: "Pajero Sport",
    year: 2024,
    seats: 7,
    price_per_day: 950000,
    fuel_type: "Diesel",
    transmission: "Matic",
    image: "/images/mitsubishi-pajero-sport.png",
    description:
      "Mitsubishi Pajero Sport adalah SUV tangguh dengan kemampuan off-road yang luar biasa, cocok untuk petualangan di segala medan.",
    availability: false,
  },
  {
    id: 9,
    name: "Toyota Agya",
    brand: "Toyota",
    model: "Agya",
    year: 2024,
    seats: 5,
    price_per_day: 300000,
    fuel_type: "Bensin",
    transmission: "Manual",
    image: "/images/toyota-agya.png",
    description:
      "Toyota Agya adalah mobil kompak dengan desain sederhana dan efisiensi bahan bakar yang sangat baik, cocok untuk penggunaan perkotaan.",
    availability: true,
  },
  {
    id: 10,
    name: "Toyota Yaris",
    brand: "Toyota",
    model: "Yaris",
    year: 2020,
    seats: 5,
    price_per_day: 550000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/toyota-yaris.png",
    description:
      "Toyota Yaris adalah mobil hatchback dengan desain modern, performa responsif, dan efisiensi bahan bakar yang tinggi, ideal untuk perjalanan sehari-hari.",
    availability: true,
  },
  {
    id: 11,
    name: "Honda Brio",
    brand: "Honda",
    model: "Brio",
    year: 2024,
    seats: 5,
    price_per_day: 350000,
    fuel_type: "Bensin",
    transmission: "Manual",
    image: "/images/honda-brio.png",
    description:
      "Honda Brio adalah mobil kompak dengan desain stylish dan efisiensi bahan bakar yang baik, cocok untuk penggunaan perkotaan.",
    availability: true,
  },
  {
    id: 12,
    name: "Honda Mobilio",
    brand: "Honda",
    model: "Mobilio",
    year: 2022,
    seats: 7,
    price_per_day: 400000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/honda-mobilio.png",
    description:
      "Honda Mobilio adalah MPV dengan kapasitas 7 penumpang dan desain yang praktis untuk keluarga besar.",
    availability: true,
  },
  {
    id: 13,
    name: "Honda Jazz",
    brand: "Honda",
    model: "Jazz",
    year: 2020,
    seats: 5,
    price_per_day: 500000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/honda-jazz.png",
    description:
      "Honda Jazz adalah mobil hatchback yang praktis dan stylish dengan ruang kabin yang luas dan efisiensi bahan bakar yang baik.",
    availability: true,
  },
  {
    id: 14,
    name: "Toyota Alphard",
    brand: "Toyota",
    model: "Alphard",
    year: 2020,
    seats: 7,
    price_per_day: 2000000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/toyota-alphard.png",
    description:
      "Toyota Alphard adalah MPV premium yang menawarkan kenyamanan dan kemewahan terbaik untuk perjalanan keluarga atau bisnis.",
    availability: true,
  },
  {
    id: 15,
    name: "Toyota Hiace",
    brand: "Toyota",
    model: "Hiace",
    year: 2020,
    seats: 15,
    price_per_day: 1500000,
    fuel_type: "Diesel",
    transmission: "Manual",
    image: "/images/toyota-hiace.png",
    description:
      "Toyota Hiace adalah kendaraan niaga dengan kapasitas besar, ideal untuk perjalanan kelompok atau transportasi komersial.",
    availability: true,
  },
  {
    id: 16,
    name: "Toyota Calya",
    brand: "Toyota",
    model: "Calya",
    year: 2020,
    seats: 7,
    price_per_day: 350000,
    fuel_type: "Bensin",
    transmission: "Manual",
    image: "/images/toyota-calya.png",
    description:
      "Toyota Calya adalah MPV ekonomis dengan kapasitas 7 penumpang, cocok untuk penggunaan sehari-hari atau perjalanan keluarga.",
    availability: true,
  },
  {
    id: 17,
    name: "Toyota Rush",
    brand: "Toyota",
    model: "Rush",
    year: 2024,
    seats: 7,
    price_per_day: 450000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/toyota-rush.png",
    description:
      "Toyota Rush adalah SUV stylish dan tangguh yang cocok untuk perjalanan keluarga atau eksplorasi ringan.",
    availability: true,
  },
  {
    id: 18,
    name: "Toyota Raize",
    brand: "Toyota",
    model: "Raize",
    year: 2021,
    seats: 5,
    price_per_day: 400000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/toyota-raize.png",
    description:
      "Toyota Raize adalah SUV kompak dengan desain modern dan fitur canggih, cocok untuk kebutuhan mobilitas perkotaan.",
    availability: true,
  },
  {
    id: 19,
    name: "Toyota Supra",
    brand: "Toyota",
    model: "Supra",
    year: 2021,
    seats: 2,
    price_per_day: 3000000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/toyota-supra.png",
    description:
      "Toyota Supra adalah mobil sport legendaris dengan desain agresif dan performa luar biasa, cocok untuk penggemar kecepatan.",
    availability: true,
  },
  {
    id: 20,
    name: "Toyota GR86",
    brand: "Toyota",
    model: "GT86",
    year: 2021,
    seats: 4,
    price_per_day: 1500000,
    fuel_type: "Bensin",
    transmission: "Manual",
    image: "/images/toyota-gr86.png",
    description:
      "Toyota GR86 adalah mobil coupe dengan handling yang presisi dan desain sporty, ideal untuk penggemar otomotif.",
    availability: true,
  },
  {
    id: 21,
    name: "Toyota Land Cruiser",
    brand: "Toyota",
    model: "Land Cruiser",
    year: 2024,
    seats: 7,
    price_per_day: 2500000,
    fuel_type: "Diesel",
    transmission: "Matic",
    image: "/images/toyota-land-cruiser.png",
    description:
      "Toyota Land Cruiser adalah SUV premium dengan kemampuan off-road luar biasa dan kenyamanan yang optimal untuk segala jenis perjalanan.",
    availability: true,
  },
  {
    id: 22,
    name: "Toyota Corolla",
    brand: "Toyota",
    model: "Corolla",
    year: 2023,
    seats: 5,
    price_per_day: 600000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/toyota-corolla.png",
    description:
      "Toyota Corolla adalah sedan ikonik dengan desain elegan, efisiensi bahan bakar yang baik, dan performa berkendara yang halus.",
    availability: true,
  },
  {
    id: 23,
    name: "Honda City Hatchback",
    brand: "Honda",
    model: "City Hatchback",
    year: 2021,
    seats: 5,
    price_per_day: 550000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/honda-city-hatchback.png",
    description:
      "Honda City Hatchback adalah hatchback modern dengan desain elegan, performa efisien, dan kabin luas yang cocok untuk perjalanan sehari-hari.",
    availability: true,
  },
  {
    id: 24,
    name: "Daihatsu Terios",
    brand: "Daihatsu",
    model: "Terios",
    year: 2021,
    seats: 7,
    price_per_day: 450000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/daihatsu-terios.png",
    description:
      "Daihatsu Terios adalah SUV tangguh dengan desain modern, cocok untuk perjalanan keluarga dan petualangan.",
    availability: true,
  },
  {
    id: 25,
    name: "Daihatsu Sigra",
    brand: "Daihatsu",
    model: "Sigra",
    year: 2021,
    seats: 7,
    price_per_day: 300000,
    fuel_type: "Bensin",
    transmission: "Manual",
    image: "/images/daihatsu-sigra.png",
    description:
      "Daihatsu Sigra adalah MPV ekonomis dengan kapasitas 7 penumpang, ideal untuk perjalanan keluarga kecil.",
    availability: true,
  },
  {
    id: 26,
    name: "Daihatsu Xenia",
    brand: "Daihatsu",
    model: "Xenia",
    year: 2021,
    seats: 7,
    price_per_day: 400000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/daihatsu-xenia.png",
    description:
      "Daihatsu Xenia adalah MPV serbaguna dengan kenyamanan dan efisiensi yang cocok untuk perjalanan keluarga.",
    availability: true,
  },
  {
    id: 27,
    name: "Daihatsu Ayla",
    brand: "Daihatsu",
    model: "Ayla",
    year: 2020,
    seats: 5,
    price_per_day: 300000,
    fuel_type: "Bensin",
    transmission: "Manual",
    image: "/images/daihatsu-ayla.png",
    description:
      "Daihatsu Ayla adalah mobil kompak yang hemat bahan bakar dengan desain modern, ideal untuk penggunaan perkotaan.",
    availability: true,
  },
  {
    id: 28,
    name: "Daihatsu Rocky",
    brand: "Daihatsu",
    model: "Rocky",
    year: 2023,
    seats: 5,
    price_per_day: 400000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/daihatsu-rocky.png",
    description:
      "Daihatsu Rocky adalah SUV kompak dengan desain sporty dan teknologi canggih, cocok untuk mobilitas perkotaan.",
    availability: true,
  },
  {
    id: 29,
    name: "Hyundai Stargazer",
    brand: "Hyundai",
    model: "Stargazer",
    year: 2023,
    seats: 7,
    price_per_day: 500000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/hyundai-stargazer.png",
    description:
      "Hyundai Stargazer adalah MPV modern dengan desain futuristik dan fitur canggih, cocok untuk perjalanan keluarga.",
    availability: true,
  },
  {
    id: 30,
    name: "Hyundai Creta",
    brand: "Hyundai",
    model: "Creta",
    year: 2023,
    seats: 5,
    price_per_day: 600000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/hyundai-creta.png",
    description:
      "Hyundai Creta adalah SUV stylish dan praktis dengan performa tangguh, cocok untuk perjalanan jarak jauh maupun di kota.",
    availability: true,
  },
  {
    id: 31,
    name: "Hyundai Ioniq 5",
    brand: "Hyundai",
    model: "Ioniq 5",
    year: 2023,
    seats: 5,
    price_per_day: 1200000,
    fuel_type: "Listrik",
    transmission: "Matic",
    image: "/images/hyundai-ioniq5.png",
    description:
      "Hyundai Ioniq 5 adalah mobil listrik futuristik dengan desain modern dan teknologi canggih, ideal untuk perjalanan ramah lingkungan.",
    availability: true,
  },
  {
    id: 32,
    name: "Hyundai Palisade",
    brand: "Hyundai",
    model: "Palisade",
    year: 2023,
    seats: 7,
    price_per_day: 1500000,
    fuel_type: "Diesel",
    transmission: "Matic",
    image: "/images/hyundai-palisade.png",
    description:
      "Hyundai Palisade adalah SUV premium dengan kapasitas besar dan kenyamanan maksimal, cocok untuk perjalanan keluarga besar.",
    availability: true,
  },
  {
    id: 33,
    name: "Hyundai Kona Electric",
    brand: "Hyundai",
    model: "Kona Electric",
    year: 2023,
    seats: 5,
    price_per_day: 1000000,
    fuel_type: "Listrik",
    transmission: "Matic",
    image: "/images/hyundai-kona-electric.png",
    description:
      "Hyundai Kona Electric adalah SUV kompak dengan tenaga listrik sepenuhnya, menawarkan efisiensi tinggi dan desain modern.",
    availability: true,
  },
  {
    id: 34,
    name: "Hyundai Tucson",
    brand: "Hyundai",
    model: "Tucson",
    year: 2023,
    seats: 5,
    price_per_day: 700000,
    fuel_type: "Bensin",
    transmission: "Matic",
    image: "/images/hyundai-tucson.png",
    description:
      "Hyundai Tucson adalah SUV kelas menengah dengan desain elegan, performa andal, dan fitur keselamatan canggih.",
    availability: true,
  },
  {
    id: 35,
    name: "Hyundai Ioniq 6",
    brand: "Hyundai",
    model: "Ioniq 6",
    year: 2023,
    seats: 5,
    price_per_day: 1500000,
    fuel_type: "Listrik",
    transmission: "Matic",
    image: "/images/hyundai-ioniq6.png",
    description:
      "Hyundai Ioniq 6 adalah sedan listrik dengan desain aerodinamis futuristik dan teknologi canggih, cocok untuk perjalanan ramah lingkungan.",
    availability: true,
  },
  {
    id: 36,
    name: "Hyundai Santa Fe",
    brand: "Hyundai",
    model: "Santa Fe",
    year: 2023,
    seats: 7,
    price_per_day: 1400000,
    fuel_type: "Diesel",
    transmission: "Matic",
    image: "/images/hyundai-santa-fe.png",
    description:
      "Hyundai Santa Fe adalah SUV mewah dengan performa handal, ruang kabin luas, dan fitur kenyamanan premium, ideal untuk perjalanan keluarga.",
    availability: true,
  },
];
